services:
  postgres:
    image: postgres
    container_name: chatbot
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data